### ISSUE TITLE
BUILD file not found in directory 'tools/osx/crosstool'

### ISSUE THREAD

**Issue by mbs0221** [rivosinc/salus#325]
Here, I come across the following error.

```bash
~/rivosinc/salus$ rm -rf ~/.cache/bazel
~/rivosinc/salus$ make run_buildroot
# Check if the submodule needs to be initialized
if [ "$(git submodule status | grep -c '^-')" -gt 0 ]; then \
	git submodule update --init; \
fi
bazel build //:salus-all
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository local_config_cc_toolchains instantiated at:
  /home/bsmei/rivosinc/salus/WORKSPACE:29:19: in <toplevel>
  /home/bsmei/.cache/bazel/_bazel_bsmei/63f8ca0048a0a2eb0e2ab26c0d9317b1/external/rules_rivos/lib/deps.bzl:17:24: in rivos_dependencies
  /home/bsmei/.cache/bazel/_bazel_bsmei/63f8ca0048a0a2eb0e2ab26c0d9317b1/external/rules_cc/cc/repositories.bzl:28:17: in rules_cc_toolchains
  /home/bsmei/.cache/bazel/_bazel_bsmei/63f8ca0048a0a2eb0e2ab26c0d9317b1/external/rules_cc/cc/private/toolchain/cc_configure.bzl:179:27: in cc_configure
Repository rule cc_autoconf_toolchains defined at:
  /home/bsmei/.cache/bazel/_bazel_bsmei/63f8ca0048a0a2eb0e2ab26c0d9317b1/external/rules_cc/cc/private/toolchain/cc_configure.bzl:79:41: in <toplevel>
ERROR: /home/bsmei/.cache/bazel/_bazel_bsmei/63f8ca0048a0a2eb0e2ab26c0d9317b1/external/rules_cc/cc/private/toolchain/lib_cc_configure.bzl:38:45: An error occurred during the fetch of repository 'local_config_cc_toolchains':
   Traceback (most recent call last):
	File "/home/bsmei/.cache/bazel/_bazel_bsmei/63f8ca0048a0a2eb0e2ab26c0d9317b1/external/rules_cc/cc/private/toolchain/cc_configure.bzl", line 39, column 27, in cc_autoconf_toolchains_impl
		paths = resolve_labels(repository_ctx, [
	File "/home/bsmei/.cache/bazel/_bazel_bsmei/63f8ca0048a0a2eb0e2ab26c0d9317b1/external/rules_cc/cc/private/toolchain/lib_cc_configure.bzl", line 38, column 45, in resolve_labels
		return dict([(label, repository_ctx.path(Label(label))) for label in labels])
Error in path: Unable to load package for @@bazel_tools//tools/osx/crosstool:BUILD.toolchains: BUILD file not found in directory 'tools/osx/crosstool' of external repository @@bazel_tools. Add a BUILD file to a directory to mark it as a package.
ERROR: Analysis of target '//:salus-all' failed; build aborted: Unable to load package for @@bazel_tools//tools/osx/crosstool:BUILD.toolchains: BUILD file not found in directory 'tools/osx/crosstool' of external repository @@bazel_tools. Add a BUILD file to a directory to mark it as a package.
INFO: Elapsed time: 145.087s, Critical Path: 0.06s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
FAILED: 
    Fetching repository @@local_jdk; starting
    Fetching repository @@rules_java~; starting
    Fetching repository @@bazel_skylib~; starting
    Fetching repository @@apple_support~; starting
make: *** [Makefile:15：salus] Error 1
~/rivosinc/salus$ 
```

Any help would be appreciated!

**Comment by mbs0221** [comment]
This problem has been solved by using `bazel-6.0.0`.
